config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :games do 
    member do
      patch :attempted_answer
    end
  end

  # Defines the root path route ("/")
  root "games#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user  
  attr_accessor :button_label

  def attempt(user_guess)
    self.attempts_count += 1
    correct_positions, matches = GuessNumberService.call(user_guess, self)
    self.is_won = true if secret_answer == user_guess.to_i
    self.game_responses += " #{correct_positions} #{matches}," 
    self.user_attempts += " #{user_guess},"
    if self.attempts_count >= allowed_attempts_for_the_game
      self.is_won = false
      puts "Sorry, you have run out of guesses. The secret number was #{secret_answer}. You lost the game."
    end
    self.save
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name])
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :attempted_answer, :destroy]

  def index
    @games = current_user.games
    @games.each do |game|
      if game.is_won 
        game.button_label = "Watch"
      elsif game.is_won.nil? 
        game.button_label = "Continue playing"
      else
        game.button_label = "Watch"
      end
    end
  end
  
  def new
    @game = Game.new
  end

  def create
    secret = rand(1000..9999).to_s
    if game_params[:allowed_attempts_for_the_game]
      @game = Game.build(user: current_user, secret_answer: secret, allowed_attempts_for_the_game: game_params[:allowed_attempts_for_the_game])
      @game.save
    end
    redirect_to @game
  end

  def show 
  end

  def destroy
    @game.destroy!

    respond_to do |format|
      format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def attempted_answer
    puts params.inspect
    user_guessed = game_params[:attempted_answer]
    @game.attempt(user_guessed)
    if @game.is_won
      flash[:notice] = 'You won this game!!'
    end
    redirect_to @game
  end

  private

  def game_params
    params.require(:game).permit(:attempted_answer, :allowed_attempts_for_the_game)
  end

  def set_game
    @game = Game.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def main
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.erb
<div class="m-10 px-5 grid grid-cols-1 gap-2 leading-loose min-w-96">
  <div>
    <h2 class="devise-form-header inline">Number Guessing Game</h2>
      <%= link_to "New Game", new_game_path, class: "w-max rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 float-right" %>
  </div>
</div>

<div>
  <% @games.each do |game| %>
    <div class="mx-10 my-1 p-3 grid grid-cols-1 odd:bg-indigo-100 even:bg-indigo-200 rounded-md hover:bg-indigo-400">
      <div>
        <% if game.is_won %>
          <label>You won this game in <%= game.attempts_count %> attempts.</label>
        <% elsif game.is_won.nil? %>
          <label>Game is still runnig you can continue playing the game</label>
        <% else %>
          <label>You lost this game</label>
        <% end %>
        <div class="float-right flex gap-1">
          <%= link_to game.button_label, game_path(game), class: 'devise-link float-right max-w-max' %>
          <%= button_to "Delete this game", game, method: :delete, class: 'devise-link float-right max-w-max mr-2', data: { turbo_confirm: "Are you sure?"} %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/games/new.html.erb
<div class="w-max m-3">
  <%= form_with(model: @game, local: true, class: "flex items-baseline") do |form| %>
    <div class="field mb-3 flex items-center">
      <%= form.label "User attempts", class: 'text-lg text-nowrap m-3' %>
      <%= form.number_field :allowed_attempts_for_the_game, class: 'devise-input', value: 100 %>
    </div>

    <div class="actions mx-1">
      <%= form.submit "Start Game", class: 'devise-link' %>
    </div>
  <% end %>
</div>

app/views/games/show.html.erb
<div>
  <label><%= @game.allowed_attempts_for_the_game - @game.attempts_count %> Attempts remaining.</label>
  <label>Game started <%= time_ago_in_words @game.created_at %> ago</label>
</div>

<div>
  <% if @game.is_won == false %>
    <div>You lost this game!!!</div>
  <% elsif @game.is_won.nil? %>
    <%= form_with(model: @game, url: attempted_answer_game_path(@game), method: :patch, local: true, class: 'm-3 w-max flex items-center') do |form| %>
      <div class="field flex items-center mx-2">
        <%= form.label "Your guess", class: 'text-nowrap' %>&nbsp;
        <%= form.number_field :attempted_answer, class: 'devise-input', autofocus: true %>
      </div>

      <div class="actions mx-2">
        <%= form.submit "Try!", class: 'devise-link' %>
      </div>
    <% end %>
  <% else %>
    <div>Yayyyy!! You won this game!!!</div>
  <% end %>
</div>

<div class="m-3 w-max items-center grid grid-cols-1 gap-2">

  <% @game.game_responses.split(',').map(&:strip).reverse.zip(@game.user_attempts.split(',').map(&:strip).reverse) do |gr, ua| %>
    <div class="my-1">
      <div>You guessed: <%= ua %></div>
      <div>Correctly guessed numbers with right position: <%= gr[0] %></div>
      <div>Correctly guessed numbers with wrong position: <%= gr[-1] %></div>
    </div>
  <% end %>

</div>

app/views/home/main.html.erb
<div class="mt-5">Hello <%= current_user.first_name %>!!!</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Boilerplate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="flex w-full h-full grid grid-cols-1">
      <%= render "shared/flash" %>
      <%= render "shared/nav" %>

      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="notice flash-alert">
    <p><%= notice %></p>
  </div>
<% end %>

<% if alert %>
  <div class="alert flash-alert">
    <p><%= alert %></p>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="flex justify-between p-5 bg-indigo-300">
  <div class="flex items-center gap-2">
    <%= link_to "Guess The Number", root_path, class: "text-xl font-bold no-underline" %>
    <ul class="list-none flex gap-2">
      <li class="mx-5 font-medium hover:text-sky-600 duration-500"><%= link_to "Home", root_path %></li>
    </ul>
  </div>

  <ul class="list-none flex items-center gap-1 divide-x">
    <% if user_signed_in? %>
      <li><%= link_to "Play game", games_path, class: "mx-1 hover:text-sky-600 duration-500" %></li>
      <li><%= link_to "Change Password", edit_user_registration_path, class: "mx-1 hover:text-sky-600 duration-500" %></li>
      <li><%= button_to "Logout", destroy_user_session_path, method: :delete, class: "mx-1 hover:text-sky-600 duration-500" %></li>
    <% else %>
      <li><%= link_to "Login", new_user_session_path, class: "mx-5 hover:text-sky-600 duration-500" %></li>
      <li><%= link_to "Sign Up", new_user_registration_path, class: "mx-5 hover:text-sky-600 duration-500" %></li>
    <% end %>
  </ul>
</nav>